---
booktitle: Proceedings of The 8th Conference on Robot Learning
shortname: CoRL
year: '2024'
volume: '270'
start: &1 2024-11-06
end: 2024-11-09
published: 2025-01-12
conference_number: '8'
sections:
- name: Oral
  title: Oral
- name: Poster
  title: Poster
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: CoRL-2024
month: 0
cycles: false
bibtex_editor: Agrawal, Pulkit and Kroemer, Oliver and Burgard, Wolfram
editor:
- given: Pulkit
  family: Agrawal
- given: Oliver
  family: Kroemer
- given: Wolfram
  family: Burgard
title: Proceedings of Machine Learning Research
description: |
  Proceedings of The 8th Conference on Robot Learning
    Held in Munich, Germany on 06-09 November 2024

  Published as Volume 270 by the Proceedings of Machine Learning Research on 12 January 2025.

  Volume Edited by:
    Pulkit Agrawal
    Oliver Kroemer
    Wolfram Burgard

  Series Editors:
    Neil D. Lawrence
date_str: 06--09 Nov
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v270"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v270
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v270
email: ''
conference:
  name: Conference on Robot Learning
  url: https://2024.corl.org/
  location: Munich, Germany
  dates:
  - *1
  - 2024-11-07
  - 2024-11-08
  - 2024-11-09
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v270/corl24.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v270/corl24.bib
